import { query } from './index.js';
import dotenv from 'dotenv';

dotenv.config();

const migrations = `
-- Users table
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Watchlists table
CREATE TABLE IF NOT EXISTS watchlists (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  is_shared BOOLEAN DEFAULT false,
  created_by UUID REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Watchlist members (for shared watchlists)
CREATE TABLE IF NOT EXISTS watchlist_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  watchlist_id UUID REFERENCES watchlists(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  can_edit BOOLEAN DEFAULT false,
  joined_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(watchlist_id, user_id)
);

-- Watchlist items (stocks/options being watched)
CREATE TABLE IF NOT EXISTS watchlist_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  watchlist_id UUID REFERENCES watchlists(id) ON DELETE CASCADE,
  symbol VARCHAR(20) NOT NULL,
  item_type VARCHAR(20) DEFAULT 'stock', -- 'stock' or 'option'
  option_details JSONB, -- strike, expiry, type (call/put) for options
  notes TEXT,
  added_by UUID REFERENCES users(id),
  added_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(watchlist_id, symbol, item_type, option_details)
);

-- Alerts table
CREATE TABLE IF NOT EXISTS alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  symbol VARCHAR(20) NOT NULL,
  alert_type VARCHAR(50) NOT NULL, -- 'price_above', 'price_below', 'percent_change', 'volume_spike'
  trigger_value DECIMAL(20, 4) NOT NULL,
  is_active BOOLEAN DEFAULT true,
  is_triggered BOOLEAN DEFAULT false,
  triggered_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Recommendations table
CREATE TABLE IF NOT EXISTS recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL,
  recommendation_type VARCHAR(50) NOT NULL, -- 'buy', 'sell', 'hold', 'options_call', 'options_put'
  entry_price DECIMAL(20, 4) NOT NULL,
  target_price DECIMAL(20, 4),
  stop_loss DECIMAL(20, 4),
  option_details JSONB, -- For options: strike, expiry, premium, etc.
  reasoning TEXT NOT NULL,
  confidence_score DECIMAL(5, 2), -- 0-100
  status VARCHAR(20) DEFAULT 'active', -- 'active', 'hit_target', 'hit_stop', 'expired', 'closed'
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  closed_at TIMESTAMP,
  exit_price DECIMAL(20, 4),
  profit_loss_percent DECIMAL(10, 4),
  profit_loss_amount DECIMAL(20, 4)
);

-- Recommendation votes/reactions
CREATE TABLE IF NOT EXISTS recommendation_reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recommendation_id UUID REFERENCES recommendations(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  reaction_type VARCHAR(20) NOT NULL, -- 'bullish', 'bearish', 'following'
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(recommendation_id, user_id)
);

-- Chat messages
CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  room VARCHAR(100) DEFAULT 'general',
  message TEXT NOT NULL,
  message_type VARCHAR(20) DEFAULT 'text', -- 'text', 'chart_share', 'recommendation_share'
  metadata JSONB, -- For shared content
  created_at TIMESTAMP DEFAULT NOW()
);

-- Price history cache (for charting)
CREATE TABLE IF NOT EXISTS price_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL,
  timeframe VARCHAR(20) NOT NULL, -- '1d', '1w', '1m', '3m', '1y', '5y'
  data JSONB NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(symbol, timeframe)
);

-- Market Signals table (generated by the bot)
CREATE TABLE IF NOT EXISTS signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL,
  signal_type VARCHAR(50) NOT NULL, -- 'technical', 'news', 'volume', 'momentum', 'reversal', 'breakout'
  direction VARCHAR(20) NOT NULL, -- 'bullish', 'bearish', 'neutral'
  strength INTEGER NOT NULL CHECK (strength >= 1 AND strength <= 10),
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  indicators JSONB, -- Technical indicators that triggered signal
  price_at_signal DECIMAL(20, 4) NOT NULL,
  target_price DECIMAL(20, 4),
  stop_price DECIMAL(20, 4),
  timeframe VARCHAR(20), -- 'intraday', 'swing', 'position'
  confidence INTEGER CHECK (confidence >= 0 AND confidence <= 100),
  expires_at TIMESTAMP,
  is_active BOOLEAN DEFAULT true,
  outcome VARCHAR(20), -- 'hit_target', 'hit_stop', 'expired', null if active
  outcome_price DECIMAL(20, 4),
  outcome_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Market Analysis snapshots (continuous analysis)
CREATE TABLE IF NOT EXISTS market_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL,
  analysis_type VARCHAR(50) NOT NULL, -- 'technical', 'sentiment', 'momentum', 'trend'
  data JSONB NOT NULL, -- Full analysis data
  score INTEGER, -- Overall score -100 to 100
  summary TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- News items and their analysis
CREATE TABLE IF NOT EXISTS news_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20), -- Can be null for market-wide news
  headline TEXT NOT NULL,
  summary TEXT,
  source VARCHAR(100),
  url VARCHAR(500),
  published_at TIMESTAMP,
  sentiment VARCHAR(20), -- 'positive', 'negative', 'neutral'
  sentiment_score DECIMAL(5, 2), -- -1 to 1
  impact_level VARCHAR(20), -- 'high', 'medium', 'low'
  related_symbols VARCHAR(200)[], -- Other affected symbols
  analyzed_at TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Bot predictions with tracking
CREATE TABLE IF NOT EXISTS predictions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL,
  prediction_type VARCHAR(50) NOT NULL, -- 'price_target', 'direction', 'volatility', 'earnings'
  timeframe VARCHAR(50) NOT NULL, -- '1d', '1w', '1m', etc.
  prediction JSONB NOT NULL, -- The actual prediction data
  reasoning TEXT NOT NULL,
  confidence INTEGER CHECK (confidence >= 0 AND confidence <= 100),
  price_at_prediction DECIMAL(20, 4) NOT NULL,
  target_date TIMESTAMP,
  outcome JSONB, -- Actual outcome when resolved
  accuracy_score DECIMAL(5, 2), -- How accurate was the prediction (0-100)
  is_resolved BOOLEAN DEFAULT false,
  resolved_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- User notifications queue
CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL, -- 'signal', 'alert', 'news', 'prediction', 'recommendation'
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  data JSONB, -- Additional data (symbol, signal_id, etc.)
  priority VARCHAR(20) DEFAULT 'normal', -- 'urgent', 'high', 'normal', 'low'
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Tracked symbols for the bot to monitor
CREATE TABLE IF NOT EXISTS tracked_symbols (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(200),
  sector VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  priority INTEGER DEFAULT 5, -- 1-10, higher = more frequent scans
  last_scanned_at TIMESTAMP,
  added_by UUID REFERENCES users(id),
  added_at TIMESTAMP DEFAULT NOW()
);

-- Bot activity log
CREATE TABLE IF NOT EXISTS bot_activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  activity_type VARCHAR(50) NOT NULL, -- 'scan', 'signal', 'news_fetch', 'prediction', 'alert_check'
  symbol VARCHAR(20),
  details JSONB,
  status VARCHAR(20), -- 'success', 'error', 'skipped'
  error_message TEXT,
  duration_ms INTEGER,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_watchlist_items_symbol ON watchlist_items(symbol);
CREATE INDEX IF NOT EXISTS idx_alerts_user_active ON alerts(user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_alerts_symbol ON alerts(symbol);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON recommendations(status);
CREATE INDEX IF NOT EXISTS idx_recommendations_symbol ON recommendations(symbol);
CREATE INDEX IF NOT EXISTS idx_chat_messages_room ON chat_messages(room, created_at);
CREATE INDEX IF NOT EXISTS idx_price_cache_symbol ON price_cache(symbol, timeframe);
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_active ON signals(is_active, created_at);
CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type, direction);
CREATE INDEX IF NOT EXISTS idx_market_analysis_symbol ON market_analysis(symbol, created_at);
CREATE INDEX IF NOT EXISTS idx_news_items_symbol ON news_items(symbol, published_at);
CREATE INDEX IF NOT EXISTS idx_predictions_symbol ON predictions(symbol, is_resolved);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read, created_at);
CREATE INDEX IF NOT EXISTS idx_tracked_symbols_active ON tracked_symbols(is_active, priority);
CREATE INDEX IF NOT EXISTS idx_bot_activity_log_type ON bot_activity_log(activity_type, created_at);
`;

async function migrate() {
  console.log('🔄 Running database migrations...');
  try {
    await query(migrations);
    console.log('✅ Migrations completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  }
}

migrate();
